### ISSUE TITLE
Question about the implementation of nvme_ns_read()

### ISSUE THREAD

**Issue by sunyb-dot** [linux-nvme/libnvme#617]
I have a question about the implementation of `nvme_ns_read()`.
The declaration says the argument `offset` is a LBA offset.
```
/**
 * nvme_ns_read() - Read from a namespace
 * @n:		Namespace instance
 * @buf:	Buffer into which the data will be transferred
 * @offset:	LBA offset of @n
 * @count:	Number of sectors in @buf
 *
 * Return: Number of sectors read or -1 on error.
 */
int nvme_ns_read(nvme_ns_t n, void *buf, off_t offset, size_t count);
```

But in the implementation it called `nvme_bytes_to_lba()`, which treats offset as a byte offset.

```
static int nvme_bytes_to_lba(nvme_ns_t n, off_t offset, size_t count,
			    __u64 *lba, __u16 *nlb)
{
	int bs;

	bs = nvme_ns_get_lba_size(n);
	if (!count || offset & bs || count & bs) {
		errno = EINVAL;
		return -1;
	}

       
	*lba = offset >> n->lba_shift;        // highlight: This line treats offset as byte offset
	*nlb = (count >> n->lba_shift) - 1;

	return 0;
}
```
it seems there're some conflict need to be resolved...

**Comment by igaw** [comment]
As far I can tell the indent here to have the `offset` expressed in bytes  (see the type of `offset`) but it needs to be a multiple of the block size. See the recent two fixed in this function about this topic:

- 3593d9776d8e ("tree: Fix offset argument check in nvme_bytes_to_lba")
- 01c6055e5602 ("tree: Fix argument check in nvme_bytes_to_lba")

Obviously, the documentation could be better. Care to send a fix?
